### ISSUE TITLE
 package the library using the Angular Package Format (https://goo.gl/jB3GVv).

### ISSUE THREAD

**Issue by SangeetaJ** [jqwidgets/jQWidgets#229]
while installing this package I get error by angular cli. Please check out below :
```

Error: C:\XXXX\XXXX\gqairmkkp.github\node_modules\jqwidgets-scripts\jqwidgets-ts\angular_jqxkanban.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Sangeeta\Scratch CRM\gqairmkkp.github\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:767:23)
    at C:\Sangeeta\Scratch CRM\gqairmkkp.github\node_modules\@ngtools\webpack\src\loader.js:41:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

can this be fixed ?

**Comment by bmarkov** [comment]
Use jqwidgets-ng package. It is buit using the angular module packaging and is the recommended way to use angular components. The error which you get is because you use a deprecated way.
