### ISSUE TITLE
Angular - jqxSplitLayout not initializing, returns error

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#515]
When initializing jqxSplitLayout in Angular, it returns the following error:
```
jqxsplitlayout.js:8 Uncaught ReferenceError: b is not defined
    at _wrapNativeSuper (jqxsplitlayout.js:8:1928)
    at 608 (jqxsplitlayout.js:8:6258)
    at __webpack_require__ (bootstrap:19:1)
    at 757 (jqwidgets-ng-jqxpanel.mjs:262:1)
    at __webpack_require__ (bootstrap:19:1)
    at 6747 (app.component.html:1:32)
    at __webpack_require__ (bootstrap:19:1)
    at 4431 (environment.ts:16:71)
    at __webpack_require__ (bootstrap:19:1)
    at __webpack_exec__ (main.ts:12:37)
```

**To Reproduce**
1. Create new project
2. Add jqwidgets-ng
3. Load jqxSplitLayout

Demos:
Angular 14: 
[proj.zip](https://github.com/jqwidgets/jQWidgets/files/8879479/proj.zip)

**Comment by bmarkov** [comment]
fixed
